# Generated by Django 5.0.1 on 2024-08-28 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0001_initial'),
        ('servidores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='codigo_identificacao',
            field=models.CharField(default='DEFAULT_VALUE', max_length=20),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='servidor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servidores.servidor'),
        ),
    ]
