# Generated by Django 5.0.1 on 2024-08-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0002_assinatura_codigo_identificacao_assinatura_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='codigo_identificacao',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
